[project]
authors = ["Jenesaispas"]
entry = "main.sw"
license = "Apache-2.0"
name = "seller_contract"

[dependencies]
seller_abi = {path = "../seller_abi"}
floor_abi = {path = "../floor_abi"}
vendor_abi = { path = "../vendor_abi" }
owner_wallet_abi = {path = "../owner_wallet_abi"}
bond_token_abi = { path = "../bond_token_abi" }
